## Questão 1
Crie um array com os números de 0 a 9, utilize somente 1 dimensão.

In [1]:
import numpy as np

array_1d = np.arange(10)
print("Array 1D de 0 a 9:", array_1d)

Array 1D de 0 a 9: [0 1 2 3 4 5 6 7 8 9]


## Questão 2
Crie um array com os números de 0 a 9 como o exercício anterior, mas utilize List Comprehensions

In [2]:
array_1d_listcomp = np.array([i for i in range(10)])
print("Array 1D com List Comprehensions:", array_1d_listcomp)

Array 1D com List Comprehensions: [0 1 2 3 4 5 6 7 8 9]


## Questão 3
Crie um array com os números de 0 a 8, utilize 2 dimensões, ou seja, com 3 linhas (3x3).

In [3]:
array_2d = np.arange(9).reshape(3, 3)
print("Array 2D 3x3 de 0 a 8:\n", array_2d)

Array 2D 3x3 de 0 a 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


## Questão 4
Crie um array do tipo float, com 10 números de sua escolha, mas utilize 32 bits/4 bytes.

In [4]:
array_float = np.array([1.5, 2.3, 3.6, 4.1, 5.9, 6.0, 7.7, 8.8, 9.2, 10.4], dtype=np.float32)
print("Array float32 com 10 números:\n", array_float)
print("Tipo de dados:", array_float.dtype)

Array float32 com 10 números:
 [ 1.5  2.3  3.6  4.1  5.9  6.   7.7  8.8  9.2 10.4]
Tipo de dados: float32


## Questão 5
Crie um array com os números de 1 a 20, escolhendo o tipo de dado que ocupará o menor espaço da memória. Em seguida, imprima o quanto ele ocupou em bytes.

In [5]:
array_min_mem = np.arange(1, 21, dtype=np.int8)
print("Array com números de 1 a 20 usando int8:", array_min_mem)
print("Espaço ocupado em bytes:", array_min_mem.nbytes)

Array com números de 1 a 20 usando int8: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Espaço ocupado em bytes: 20


## Questão 6
Crie uma matriz 2x2 e imprima o primeiro elemento da primeira linha, e o último elemento da última linha.

In [6]:
matriz_2x2 = np.array([[1, 2], [3, 4]])

primeiro_elemento = matriz_2x2[0, 0]
print("Primeiro elemento da primeira linha:", primeiro_elemento)

ultimo_elemento = matriz_2x2[-1, -1]
print("Último elemento da última linha:", ultimo_elemento)

Primeiro elemento da primeira linha: 1
Último elemento da última linha: 4


## Questão 7
Gere uma array 3x3 com números inteiros aleatórios entre 5 e 20. Então imprima a primeira coluna e última linha.

In [7]:
import numpy as np

array_3x3 = np.random.randint(5, 21, (3, 3))
print("Array 3x3 com números aleatórios entre 5 e 20:\n", array_3x3)

primeira_coluna = array_3x3[:, 0]
print("Primeira coluna:", primeira_coluna)

ultima_linha = array_3x3[-1, :]
print("Última linha:", ultima_linha)

Array 3x3 com números aleatórios entre 5 e 20:
 [[11 16 12]
 [ 7 20 16]
 [10  6 19]]
Primeira coluna: [11  7 10]
Última linha: [10  6 19]


## Questão 8
Crie uma matriz 3x3 aleatória. Percorra linha por linha com um laço e imprima a soma de cada linha.

In [8]:
matriz_3x3 = np.random.randint(1, 10, (3, 3))
print("Matriz 3x3 aleatória:\n", matriz_3x3)

for i, linha in enumerate(matriz_3x3):
    soma_linha = np.sum(linha)
    print(f"Soma da linha {i + 1}: {soma_linha}")

Matriz 3x3 aleatória:
 [[8 5 9]
 [6 8 5]
 [1 8 7]]
Soma da linha 1: 22
Soma da linha 2: 19
Soma da linha 3: 16


## Questão 9
Gere um array com os valores pares de 0 a 100 com list comprehension.

In [9]:
array_pares = np.array([i for i in range(0, 101, 2)])
print("Array com valores pares de 0 a 100:", array_pares)

Array com valores pares de 0 a 100: [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


## Questão 10
Crie uma array 4x9 com valores quaisquer, redimensione para as dimensões 36 e 6x6.

In [10]:
array_4x9 = np.arange(36).reshape(4, 9)
print("Array 4x9 inicial:\n", array_4x9)

array_36 = array_4x9.flatten()
print("Array com 36 elementos:\n", array_36)

array_6x6 = array_4x9.reshape(6, 6)
print("Array 6x6:\n", array_6x6)

Array 4x9 inicial:
 [[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]
Array com 36 elementos:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
Array 6x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


## Questão 11
Crie uma função que receba três arrays de mesmo formato, então retorne elas concatenadas em uma só. Se as matrizes recebidas não forem do mesmo formato, gere uma exceção.

In [11]:
def concatena_arrays(array1, array2, array3):
    if array1.shape == array2.shape == array3.shape:
        return np.concatenate((array1, array2, array3), axis=0)
    else:
        raise ValueError("Os arrays não têm o mesmo formato!")

array_a = np.ones((2, 2))
array_b = np.zeros((2, 2))
array_c = np.full((2, 2), 5)

try:
    array_concatenado = concatena_arrays(array_a, array_b, array_c)
    print("Array concatenado:\n", array_concatenado)
except ValueError as e:
    print(e)

Array concatenado:
 [[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [5. 5.]
 [5. 5.]]


## Questão 12
Crie uma função que divida um array em N pedaços, mas mantenha só os valores absolutos dos valores deste array.

In [12]:
import numpy as np

def dividir_abs(array, n):
    abs_array = np.abs(array)
    return np.array_split(abs_array, n)

array_exemplo = np.array([-10, -5, 0, 5, 10, -15])
pedacos = dividir_abs(array_exemplo, 3)
print("Array dividido em 3 pedaços com valores absolutos:", pedacos)

Array dividido em 3 pedaços com valores absolutos: [array([10,  5]), array([0, 5]), array([10, 15])]


## Questão 13
Crie uma função que receba um array e retorne quantos números positivos ele contém.

In [13]:
def contar_positivos(array):
    return np.sum(array > 0)

array_exemplo = np.array([-1, 2, 3, -4, 5])
num_positivos = contar_positivos(array_exemplo)
print("Quantidade de números positivos:", num_positivos)

Quantidade de números positivos: 3


## Questão 14
Crie uma função que receba uma matriz e retorne os índices dos números que são divisíveis por 3.

In [14]:
def indices_divisiveis_por_3(matriz):
    return np.argwhere(matriz % 3 == 0)

matriz_exemplo = np.array([[3, 5, 6], [7, 9, 12]])
indices = indices_divisiveis_por_3(matriz_exemplo)
print("Índices dos números divisíveis por 3:", indices)

Índices dos números divisíveis por 3: [[0 0]
 [0 2]
 [1 1]
 [1 2]]


## Questão 15
Crie uma função que diga se um array possui números negativos.

In [15]:
def possui_negativos(array):
    return np.any(array < 0)

array_exemplo = np.array([1, -2, 3, 4])
tem_negativos = possui_negativos(array_exemplo)
print("O array possui números negativos?", tem_negativos)

O array possui números negativos? True


## Questão 16
Crie uma função que remova os números negativos de um array.

In [16]:
def remover_negativos(array):
    return array[array >= 0]

array_exemplo = np.array([-1, 2, -3, 4, -5])
array_sem_negativos = remover_negativos(array_exemplo)
print("Array sem números negativos:", array_sem_negativos)

Array sem números negativos: [2 4]


## Questão 17
Crie uma função que receba um número inicial e final, e uma array. A função deve retornar uma nova array somente com os números dentro deste intervalo.

In [17]:
def filtrar_intervalo(array, inicio, fim):
    return array[(array >= inicio) & (array <= fim)]

array_exemplo = np.array([1, 5, 10, 15, 20])
array_filtrada = filtrar_intervalo(array_exemplo, 5, 15)
print("Array filtrada dentro do intervalo [5, 15]:", array_filtrada)

Array filtrada dentro do intervalo [5, 15]: [ 5 10 15]


## Questão 18
Crie uma função que ordene uma matriz e remova todos os números ímpares.

In [18]:
def ordenar_remover_impares(matriz):
    matriz_ordenada = np.sort(matriz, axis=None)
    return matriz_ordenada[matriz_ordenada % 2 == 0]

matriz_exemplo = np.array([[3, 8, 5], [4, 7, 2]])
matriz_pares_ordenada = ordenar_remover_impares(matriz_exemplo)
print("Matriz ordenada com apenas números pares:", matriz_pares_ordenada)

Matriz ordenada com apenas números pares: [2 4 8]


## Questão 19
Realize o mesmo exercício anterior, mas remova valores duplicados.

In [19]:
def ordenar_remover_impares_unicos(matriz):
    matriz_ordenada = np.sort(matriz, axis=None)
    matriz_pares_unicos = np.unique(matriz_ordenada[matriz_ordenada % 2 == 0])
    return matriz_pares_unicos

matriz_exemplo = np.array([[3, 8, 5], [4, 7, 2], [8, 4, 2]])
matriz_pares_ordenada_unicos = ordenar_remover_impares_unicos(matriz_exemplo)
print("Matriz ordenada com apenas números pares e sem duplicados:", matriz_pares_ordenada_unicos)

Matriz ordenada com apenas números pares e sem duplicados: [2 4 8]
